require('treesitter_conf')
require('telescope_conf')
require('cmp_conf')
require('nvim-autopairs').setup {}
require('Comment').setup()
require('vim-better-whitespace_conf')
require('undotree_conf')
require('vim-slime_conf')
require('nvim-ts-rainbow_conf')
require('vim-easy-align_conf')
require('indent-blankline_conf')
require('nvim-web-devicons_conf')
require('nvim-tree_conf')
require('luasnip_conf')
require('lualine_conf')
require('bufferline_conf')
require('dap_conf')
require('dap-python_conf')
require('dap-ui_conf')
require('firenvim_conf')
require('gruvbox_conf')
require('neorg_conf')
require('trouble_conf')
require('toggleterm_conf')
require('neovide_conf')
require('which-key_conf')
require('fugitive_conf')
require('vim-go_conf')
require('true-zen_conf')
require('twilight_conf')
require('notify').setup {}
require('gitsigns_conf')
require('symbols-outline_conf')
require('nvim-surround').setup {}
require('marks').setup {}
require('peek_conf')
require('boole_conf')
require('vifm_conf')
require('zen_mode_conf')
require('dashboard_conf')
