return require('packer').startup(function()
    use 'wbthomason/packer.nvim'
    use 'scrooloose/nerdtree'
    use 'majutsushi/tagbar'
    use 'mbbill/undotree'
    use 'christoomey/vim-tmux-navigator'
    use 'jpalardy/vim-slime'
    use 'kshenoy/vim-signature'
    use 'junegunn/vim-peekaboo'
    use 'wesQ3/vim-windowswap'
    use 'tpope/vim-eunuch'
    use 'tpope/vim-unimpaired'
    use 'tpope/vim-commentary'
    use 'tpope/vim-repeat'
    use 'tpope/vim-surround'
    use 'wellle/targets.vim'
    use 'jiangmiao/auto-pairs'
    use 'ntpeters/vim-better-whitespace'
    use 'terryma/vim-multiple-cursors'
    use 'godlygeek/tabular'
    use 'vim-airline/vim-airline'
    use 'kana/vim-textobj-user'
    use 'kana/vim-textobj-line'
    use 'kana/vim-textobj-entire'
    use 'Julian/vim-textobj-variable-segment'
    use 'michaeljsmith/vim-indent-object'
    use 'morhetz/gruvbox'
    use 'luochen1990/rainbow'
    use 'SirVer/ultisnips'
    use 'honza/vim-snippets'
    use {
        'ms-jpq/coq_nvim',
        branch = 'coq'
    }
    use {
        'ms-jpq/coq.artifacts',
        branch = 'artifacts'
    }
    use 'tpope/vim-fugitive'
    use 'mhinz/vim-signify'
    use 'tpope/vim-rhubarb'
    use 'plasticboy/vim-markdown'
    use 'mattn/emmet-vim'
    use 'neovimhaskell/haskell-vim'
    use 'amiorin/vim-textile'
    use 'fatih/vim-go'
    use 'nvim-lua/plenary.nvim'
    use 'nvim-telescope/telescope.nvim'
    use 'nvim-treesitter/nvim-treesitter'
    use 'neovim/nvim-lspconfig'
    use 'williamboman/nvim-lsp-installer'
end)
